### ISSUE TITLE
README.md has typo

### ISSUE THREAD

**Issue by DongjinS** [shumbo/grpc-web-error-details#4]
Hi 👋 

First of all, I was able to decode grpc-web-error-details-bin using "grpc-web-error-details". Thanks for your work.

While using grpc-web-error-details, I found a typo in README.MD.
`v.getDescription` ➡️ `v.getDescription()`
<img width="912" alt="image" src="https://user-images.githubusercontent.com/46275039/178390717-34566b9a-f5b9-4e57-99be-fc647ff66868.png">

**Comment by shumbo** [comment]
@DongjinS Thanks for letting me know! Yes, that should have been a call to the function, so `getDescription()`. If you want to make a PR, I'd be happy to merge it in. Otherwise, I will fix this myself and refer to you and this issue on the commit message.

**Comment by DongjinS** [comment]
@shumbo I made PR here:) https://github.com/shumbo/grpc-web-error-details/pull/5

**Comment by shumbo** [comment]
@DongjinS Merged the PR. Thanks again for your help!
